### ISSUE TITLE
[Improvement]: modify the parameter transfer method for flink optimize

### ISSUE THREAD

**Issue by xujiangfeng001** [NetEase/amoro#1789]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

At present, when `flink optimize` is started, only `jobmanager.memory` and `taskmanager.memory `are supported for task parameter transfer methods.If users want to modify some tuning parameters of `flink optimize`, they can only use the `flink-conf.yaml` method to modify them.

### How should we improve?

The following code：

```
  protected String buildOptimizerStartupArgsString(Resource resource) {
    String taskManagerMemory = PropertyUtil.checkAndGetProperty(resource.getProperties(),
        TASK_MANAGER_MEMORY_PROPERTY);
    String jobManagerMemory = PropertyUtil.checkAndGetProperty(resource.getProperties(), JOB_MANAGER_MEMORY_PROPERTY);
    String jobPath = getAMSHome() + "/plugin/optimize/OptimizeJob.jar";
    long memory = Long.parseLong(jobManagerMemory) + Long.parseLong(taskManagerMemory) * resource.getThreadCount();
    return String.format("%s/bin/flink run -m yarn-cluster -ytm %s -yjm %s -c %s %s -m %s %s",
        getFlinkHome(), taskManagerMemory, jobManagerMemory,
        FlinkOptimizer.class.getName(), jobPath, memory,
        super.buildOptimizerStartupArgsString(resource));
  }
```

Firstly, users must define` jobmanager.memory` and `taskmanager.memory` in order to start the `flink optimizer` properly, and cannot use the configuration parameters in `flink-conf.yaml`.

Secondly, I guess that `-yD <property=value>` should be supported for parameter passing, so that the `flink-optimizer `can support more parameters.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xujiangfeng001** [comment]
cc @zhoujinsong @shidayang @wangtaohz @YesOrNo828 .

**Comment by majin1102** [comment]
Hi xujiangfeng001,

Thank you for taking the time to report the issue you encountered in our project. We appreciate your feedback and would like to invite you to contribute to our project by submitting a pull request to fix the issue.

We believe that your contribution would be very valuable, and we are happy to help you get started with contributing. Please take a look at our contribution guide at [contribution guide](https://amoro.netease.com/how-to-contribute/) and feel free to reach out to us(@shidayang @zhoujinsong) if you have any questions.

**Comment by wangtaohz** [comment]
I agree to provide a more generic method, such as using `-yD <property=value>`, to support more parameter configurations when starting the `flink-optimizer`.

But, the two parameters `jobmanager.memory` and `taskmanager.memory` are a little special. They are forced to be configured in order to obtain the accurate memory usage of the optimizer, like:
<img width="1894" alt="image" src="https://github.com/NetEase/amoro/assets/103108928/e59de45c-11c0-4e0c-a529-054dc227c7a4">

If new parameter settings allow memory to be set from `flink-conf.yaml`, we have to consider how to obtain the value of memory.

**Comment by zhongqishang** [comment]
+1 for this.

> we have to consider how to obtain the value of memory.

I think we can report resources to ams on the optimizer side, for the external optimizer, the resource can also be displayed.

BTW, I think that the yarn submission method can be changed from perjob to application mode. 
One is because perjob was deprecated in version 1.15, 
and the configuration( include jobmanager.memory/taskmanager.memory) is all configured via `-D`, which is more convenient to provide a general solution.

**Comment by wangtaohz** [comment]
> 
> I think we can report resources to ams on the optimizer side, for the external optimizer, the resource can also be displayed.
> 
> ```
> MemorySize jobMemorySize = env.getConfiguration().get(JobManagerOptions.TOTAL_PROCESS_MEMORY);
> MemorySize taskMemorySize = env.getConfiguration().get(TaskManagerOptions.TOTAL_PROCESS_MEMORY);
> int parallelism = env.getParallelism();
> ```

It looks practical. 👍
The memory can be reported to AMS during registration.

**Comment by xujiangfeng001** [comment]
> > I think we can report resources to ams on the optimizer side, for the external optimizer, the resource can also be displayed.
> > ```
> > MemorySize jobMemorySize = env.getConfiguration().get(JobManagerOptions.TOTAL_PROCESS_MEMORY);
> > MemorySize taskMemorySize = env.getConfiguration().get(TaskManagerOptions.TOTAL_PROCESS_MEMORY);
> > int parallelism = env.getParallelism();
> > ```
> 
> It looks practical. 👍 The memory can be reported to AMS during registration.

I will keep the original logic and report memory resources to AMS.
