### ISSUE TITLE
[Bug]: Fix AMS's classpath order not consistent

### ISSUE THREAD

**Issue by link3280** [NetEase/amoro#2218]
### What happened?

The script `ams.sh` uses `find` to generate the classpath, but the files that `find` produced are sorted by file creation time which makes the jar order inconsistent across multiple machines. That leads to weird class conflict issues.

### Affects Versions

0.6.0

### What engines are you seeing the problem on?

AMS

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
@link3280 
I understand the motivation behind this improvement, but I'm more interested in knowing if you encountered any conflict issues due to the order of the jar in the classpath.

Depending on the order of jars is a rather difficult-to-manage approach. Perhaps we should instead figure out the root cause of conflicts and try to resolve them.

**Comment by link3280** [comment]
@zhoujinsong My case may not be a common one. I overwrote some iceberg classes and packaged them into `amoro-core`.

**Comment by zhoujinsong** [comment]
> @zhoujinsong My case may not be a common one. I overwrote some iceberg classes and packaged them into `amoro-core`.

Got it.
