### ISSUE TITLE
[Improvement]: Improve full optimizing trigger condition

### ISSUE THREAD

**Issue by zhongqishang** [NetEase/amoro#2248]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

There are multiple segment files in a table, which can be merged into one file, but the merge is not triggered.

iceberg table format
upsert : false

### How should we improve?

Improve trigger condition

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangtaohz** [comment]
The default value of this table property `self-optimizing.full.trigger.interval` is `-1`, which means full optimizing will not be triggered by default.

I think configuring this parameter to trigger periodic full optimizing can be helpful for the scenario you report.

Do you have any new idea about triggering full optimizing? @zhongqishang

**Comment by zhongqishang** [comment]
@wangtaohz Sorry for not providing complete information, I have already opened the full optimizing. 
The table is a partition table, some partitions have a large number of segment files in which are not merged.

**Comment by zhoujinsong** [comment]
@zhongqishang Thanks a lot for bringing this improvement up.

I also agree that we should improve the existing optimizing strategy by merging multiple segment files generated by Minor into the target size, in order to prevent the files from staying at the size of the segment file. Considering that we currently do not open full optimizing by default, V2 tables must wait for enough delete records before they have a chance to merge to the target size, while V1 tables cannot merge to the target size at all.

However, as described in #1316, I think the process of merging files to the target size within a small scope is more suitable to be classified as Major Optimizing.

**Comment by wangtaohz** [comment]
> @wangtaohz Sorry for not providing complete information, I have already opened the full optimizing.
The table is a partition table, some partitions have a large number of segment files in which are not merged.

Have you identified the cause? This phenomenon is not as expected. @zhongqishang

**Comment by zhongqishang** [comment]
> Have you identified the cause? This phenomenon is not as expected. @zhongqishang

Two points:

1. The FULL trigger condition does not include segment conditions, I submitted a PR to solve it.
2. As zhoujingsong mentioned, the segment file merging is missing during the Major compation stage. I will solve it after knowing more about it。

**Comment by zhongqishang** [comment]
Contained in #2332
